[build]	
    command = "npm run build"
    build = "vite build"
    functions = "netlify/functions"
    publish = "dist"

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200    