[build]	
    command = "vite build"
    functions = "netlify/functions"
    publish = "dist

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"